[tool.poetry]
name = "git-delete-branch"
version = "0.1.0"
description = ""
authors = ["Ren Dela Cruz <ren_delacruz@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true
strict = true
warn_unreachable = true
enable_error_code = [
    "redundant-expr",
    "possibly-undefined",
    "truthy-bool",
    "explicit-override",
]
