[tool.poetry]
name = "git-delete-branch"
version = "0.1.0"
description = ""
authors = ["Ren Dela Cruz <ren_delacruz@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
git-delete-branch = "git_delete_branch.cli:say_hello"
