[tool.poetry]
name = "git-branch-cleaner"
version = "0.1.0"
description = ""
authors = ["Ren Dela Cruz <ren_delacruz@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
git-branch-cleaner = "git_branch_cleaner.cli:say_command"
